#this file is generated by AI


import streamlit as st
import requests

st.title("🏥 Insurance Premium Category Predictor")
st.markdown("Enter your details to get a predicted insurance premium category.")

# Create the form
with st.form("prediction_form"):
    col1, col2 = st.columns(2)
    
    with col1:
        age = st.number_input("Age", min_value=1, max_value=120, value=30)
        weight = st.number_input("Weight (kg)", min_value=1.0, max_value=300.0, value=70.0)
        height = st.number_input("Height (cm)", min_value=50.0, max_value=250.0, value=175.0)
        income_lpa = st.number_input("Income (Lakhs per annum)", min_value=0.1, max_value=100.0, value=5.0)
    
    with col2:
        smoker = st.selectbox("Smoker?", options=["false", "true"])
        city = st.text_input("City", value="Mumbai")
        occupation = st.selectbox(
            "Occupation",
            options=["retired", "freelancer", "student", "government_job", 
                     "business_owner", "unemployed", "private_job"]
        )
    
    submitted = st.form_submit_button("🔮 Predict Premium", use_container_width=True)

# Handle form submission
if submitted:
    # Prepare the data
    payload = {
        "age": age,
        "weight": weight,
        "height": height,
        "income_lpa": income_lpa,
        "smoker": smoker == "true",
        "city": city,
        "occupation": occupation
    }
    
    try:
        # Send POST request to the API
        response = requests.post("http://127.0.0.1:8000/predict", json=payload)
        
        if response.status_code == 200:
            result = response.json()
            category = result['predicted_premium_category']
            st.success(f"💰 Predicted Premium Category: **{category}**")
        else:
            st.error(f"Error: {response.status_code} - {response.text}")
    
    except requests.exceptions.ConnectionError:
        st.error("❌ Could not connect to the API. Make sure the FastAPI server is running.")
    except Exception as e:
        st.error(f"❌ An error occurred: {str(e)}")

# Footer
st.markdown("---")
st.caption("Make sure the FastAPI server is running: `uvicorn app:app --reload`")
